name: Go Lint

on:
    pull_request:
      branches: [ "*" ]
    workflow_call:  

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go environment
        uses: actions/setup-go@v5
        with:
          go-version: 1.23 

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60
          args: |
            ./arrays_and_loops
            ./hello_world
            ./pointers_and_structs
            ./strings_and_functions
            ./structs_public_and_private_methods
            ./switch_and_loops
            ./unit_testing